### ISSUE TITLE
Architecture layouts hierarchy gets broken starting in 0.5.9

### ISSUE THREAD

**Issue by oboxodo** [rubyatscale/visualize_packs#47]
This is a diagram generated with v0.5.8, where the architecture layouts properly reflect the hierarchy declared in packwerk.yml:

![image](https://github.com/rubyatscale/visualize_packs/assets/8324/e76c48da-00cd-4fbb-8134-6abc47e2f79c)

After upgrading to any version between v0.5.9 and 0.5.15 (current latest), this is the generated diagram for the exact same set of todos:

![image](https://github.com/rubyatscale/visualize_packs/assets/8324/9c683650-c1b6-4a91-8f7b-f4aa3ddc3ae1)

It looks to me that if architecture layouts are defined and displayed, then all efforts should be made to have their hierarchy guide the layout. At least make that an option? Would this be possible?

**Comment by shageman** [comment]
The underlying change is that I made todos influence the layout when dependencies are hidden. This is good for some graphs, for example when focused on a specific layer. This example shows that that change should be an option

**Comment by oboxodo** [comment]
This gets solved in https://github.com/rubyatscale/visualize_packs/pull/51. Closing.
