### ISSUE TITLE
Compatibility with packwerk-extensions 0.2.0

### ISSUE THREAD

**Issue by TL-David-Bauske** [rubyatscale/visualize_packs#65]
First of all: Thanks for this great gem!

packwerk-extensions (https://github.com/rubyatscale/packwerk-extensions) has recently migrated their wording from `architecture_layers` to just `layers` in their latest version. This breaks visualize_packs since it relies on the layer list in the `packwerk.yml` to be called `architecture_layers`.

As far as I can see, the fix should be simple: In `lib/visualize_packs.rb`, change

```rb
architecture_layers = (raw_config['architecture_layers'] || []) + ["NotInLayer"]
```

to

```rb
architecture_layers = (raw_config['layers'] || raw_config['architecture_layers'] || []) + ["NotInLayer"]
```

This keeps backwards compatibility and ensures support for the new key name.

**Comment by perryqh** [comment]
Thanks for the issue! We'll fix this shortly.

**Comment by schoblaska** [comment]
Fixed in https://github.com/rubyatscale/visualize_packs/pull/66
