### ISSUE TITLE
Main Branch Fix – Request for Version Update

### ISSUE THREAD

**Issue by mizoR** [rubyatscale/visualize_packs#68]
Hi there,

I'm currently using the latest release version of this gem (v0.5.23), but I encountered an issue that prevents it from working correctly in my environment. After switching to the main branch, the issue seems to be resolved and everything works as expected. It looks like my issue was fixed in [this pull request](https://github.com/rubyatscale/visualize_packs/pull/66).

Do you have any plans to release a new version?

Thanks again for all your hard work on this gem!

**Comment by tstannard** [comment]
Thanks for pointing this out - we have bumped the version and released 0.6.0 🎉
